language: cpp

dist: xenial
sudo: required
osx_image: xcode8.3
cache: ccache

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

addons:
  apt:
    packages:
      - libassimp-dev
      - libglew-dev
      - libglfw-dev
      - libglm-dev
      - libopencv-dev
  homebrew:
    packages:
      - ccache
      - eigen
      - assimp
      - glew
      - glfw
      - glm
      - opencv


before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="/usr/lib/ccache/bin/:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

  - echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
  - uname -a
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then lsb_release -a;                     fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then system_profiler SPSoftwareDataType; fi
  - env
  - which cmake
  - cmake --version
  - which $CC
  - $CC --version
  - which $CXX
  - $CXX --version
  - which ccache
  - ccache --version
  - ccache -s
  - echo "--------------------  END SYSTEM INFORMATION  --------------------"

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip2 uninstall numpy || true; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..

script:
  - make
